meta_product_name: "Woodstock"
meta_title: "Woodstock - Créez le meuble de vos envies"
meta_description: "Grâce à une visualisation 3D, modélisez votre meuble selon différents critères et observez instantanément le résultat. Une fois satisfait de votre création, nous faisons le lien avec un artisan en mesure de le réaliser."
meta_image: "cover.png"
